find_path(
	NUITRACK_INCLUDE_DIR
	NAMES "nuitrack/Nuitrack.h"
	PATHS "$ENV{NUITRACK_INCLUDE}"
	)

find_library(
	NUITRACK_LIBRARY
	NAMES "nuitrack"
	PATHS "$ENV{NUITRACK_REDIST}"
	)

find_library(
	MIDDLEWARE_LIBRARY
	NAMES "middleware"
	PATHS "$ENV{NUITRACK_REDIST}"
	)

set(NUITRACK_INCLUDE_DIR ${NUITRACK_INCLUDE_DIR})
set(NUITRACK_LIBRARY ${NUITRACK_LIBRARY})
set(MIDDLEWARE_LIBRARY ${MIDDLEWARE_LIBRARY})

if(NUITRACK_INCLUDE_DIR)
	message("NUITRACK_INCLUDE_DIR found at " ${NUITRACK_INCLUDE_DIR} )
	set (NUITRACK_INCLUDE_DIR_FOUND TRUE)
	include_directories(${NUITRACK_INCLUDE_DIR})
endif(NUITRACK_INCLUDE_DIR)

if(NUITRACK_LIBRARY)
	message("NUITRACK_LIBRARY found at " ${NUITRACK_LIBRARY} )
	set (NUITRACK_LIBRARY_FOUND TRUE)
	link_directories(${NUITRACK_LIBRARY})
endif(NUITRACK_LIBRARY)

if(MIDDLEWARE_LIBRARY)
	message("MIDDLEWARE_LIBRARY found at " ${MIDDLEWARE_LIBRARY} )
	set (MIDDLEWARE_LIBRARY_FOUND TRUE)
	link_directories(${MIDDLEWARE_LIBRARY})
endif(MIDDLEWARE_LIBRARY)